# Generated by Django 4.2.1 on 2023-06-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('joining_date', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('job_status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'emp_data',
            },
        ),
    ]
