# Generated by Django 4.2.1 on 2023-07-14 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_emp_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
